documentation:
  title: Get CMIP6 AMOC-data for historical period.
  description: The recipe downloads climate data (amoc) for historical experiments,  regrids
    the data to a 5x5 grid and provides the climatological mean of each variable for
    the full period,  as well as for three periods within the historical period.
  authors:
  - grusdt_britta
  maintainer:
  - grusdt_britta
preprocessors:
  general:
    extract_named_regions:
      regions: atlantic_arctic_ocean
  climatological_mean:
    extract_named_regions:
      regions: atlantic_arctic_ocean
    climate_statistics:
      operator: mean
      period: full
  default: {}
diagnostics:
  historical:
    variables:
      amoc_CLIM:
        derive: true
        preprocessor: climatological_mean
        variable_long_name: ocean meridional overturning mass streamfunction
        short_name: msftmz
        exp: historical
        mip: Omon
        mip_era: CMIP6
        project: CMIP6
    scripts: null
    additional_datasets:
    - dataset: GISS-E2-1-G
      ensemble: r1i1p1f5
      grid: gn
      institute: NASA-GISS
      version: v20230928
    - dataset: GISS-E2-1-G
      ensemble: r(201:202)i1p1f5
      grid: gn
      institute: NASA-GISS
      version: v20231004
    - dataset: NorCPM1
      ensemble: r(1:30)i1p1f1
      grid: grz
      institute: NCC
      version:
      - v20190914
      - v20200724
  historical1:
    variables:
      amoc_CLIM:
        derive: true
        preprocessor: climatological_mean
        variable_long_name: ocean meridional overturning mass streamfunction
        short_name: msftmz
        exp: historical
        mip: Omon
        mip_era: CMIP6
        project: CMIP6
        timerange: 1951/1980
    scripts: null
    additional_datasets:
    - dataset: NorCPM1
      ensemble: r(1:30)i1p1f1
      grid: grz
      institute: NCC
      version: v20200724
  historical2:
    variables:
      amoc_CLIM:
        derive: true
        preprocessor: climatological_mean
        variable_long_name: ocean meridional overturning mass streamfunction
        short_name: msftmz
        exp: historical
        mip: Omon
        mip_era: CMIP6
        project: CMIP6
        timerange: 1961/1990
    scripts: null
    additional_datasets:
    - dataset: NorCPM1
      ensemble: r(1:30)i1p1f1
      grid: grz
      institute: NCC
      version: v20200724
  historical3:
    variables:
      amoc_CLIM:
        derive: true
        preprocessor: climatological_mean
        variable_long_name: ocean meridional overturning mass streamfunction
        short_name: msftmz
        exp: historical
        mip: Omon
        mip_era: CMIP6
        project: CMIP6
        timerange: 1991/2014
    scripts: null
    additional_datasets:
    - dataset: GISS-E2-1-G
      ensemble: r1i1p1f5
      grid: gn
      institute: NASA-GISS
      version: v20230928
    - dataset: GISS-E2-1-G
      ensemble: r(201:202)i1p1f5
      grid: gn
      institute: NASA-GISS
      version: v20231004
    - dataset: NorCPM1
      ensemble: r(1:30)i1p1f1
      grid: grz
      institute: NCC
      version: v20200724
datasets:
- dataset: ACCESS-CM2
  ensemble: r1i1p1f1
  grid: gn
  institute: CSIRO-ARCCSS
  version: v20191108
- dataset: ACCESS-CM2
  ensemble: r2i1p1f1
  grid: gn
  institute: CSIRO-ARCCSS
  version: v20191125
- dataset: ACCESS-CM2
  ensemble: r3i1p1f1
  grid: gn
  institute: CSIRO-ARCCSS
  version: v20200306
- dataset: ACCESS-CM2
  ensemble: r(4:5)i1p1f1
  grid: gn
  institute: CSIRO-ARCCSS
  version: v20210607
- dataset: ACCESS-CM2
  ensemble: r(6:10)i1p1f1
  grid: gn
  institute: CSIRO-ARCCSS
  version: v20220819
- dataset: ACCESS-ESM1-5
  ensemble: r1i1p1f1
  grid: gn
  institute: CSIRO
  version: v20191115
- dataset: ACCESS-ESM1-5
  ensemble: r2i1p1f1
  grid: gn
  institute: CSIRO
  version: v20191128
- dataset: ACCESS-ESM1-5
  ensemble: r3i1p1f1
  grid: gn
  institute: CSIRO
  version: v20191203
- dataset: ACCESS-ESM1-5
  ensemble: r4i1p1f1
  grid: gn
  institute: CSIRO
  version: v20200529
- dataset: ACCESS-ESM1-5
  ensemble: r(6:9)i1p1f1
  grid: gn
  institute: CSIRO
  version: v20200529
- dataset: ACCESS-ESM1-5
  ensemble: r5i1p1f1
  grid: gn
  institute: CSIRO
  version: v20200601
- dataset: ACCESS-ESM1-5
  ensemble: r10i1p1f1
  grid: gn
  institute: CSIRO
  version: v20200605
- dataset: ACCESS-ESM1-5
  ensemble: r(11:20)i1p1f1
  grid: gn
  institute: CSIRO
  version: v20200803
- dataset: ACCESS-ESM1-5
  ensemble: r(21:30)i1p1f1
  grid: gn
  institute: CSIRO
  version: v20200922
- dataset: ACCESS-ESM1-5
  ensemble: r(31:40)i1p1f1
  grid: gn
  institute: CSIRO
  version: v20210525
- dataset: CAS-ESM2-0
  ensemble: r1i1p1f1
  grid: gn
  institute: CAS
  version: v20201229
- dataset: CESM2
  ensemble: r(1:11)i1p1f1
  grid: gn
  institute: NCAR
  version: v20190919
- dataset: CESM2-FV2
  ensemble: r1i1p1f1
  grid: gn
  institute: NCAR
  version: v20191120
- dataset: CESM2-FV2
  ensemble: r(2:3)i1p1f1
  grid: gn
  institute: NCAR
  version: v20200226
- dataset: CESM2-FV2
  ensemble: r1i2p2f1
  grid: gn
  institute: NCAR
  version: v20220915
- dataset: CESM2-WACCM
  ensemble: r(1:3)i1p1f1
  grid: gn
  institute: NCAR
  version: v20190917
- dataset: CESM2-WACCM-FV2
  ensemble: r1i1p1f1
  grid: gn
  institute: NCAR
  version: v20191120
- dataset: CESM2-WACCM-FV2
  ensemble: r(2:3)i1p1f1
  grid: gn
  institute: NCAR
  version: v20200226
- dataset: CanESM5
  ensemble: r(1:25)i1p1f1
  grid: gn
  institute: CCCma
  version: v20190429
- dataset: CanESM5
  ensemble: r(1:40)i1p2f1
  grid: gn
  institute: CCCma
  version: v20190429
- dataset: CanESM5-1
  ensemble: r(1:20)i1p1f1
  grid: gn
  institute: CCCma
  version: v20190429
- dataset: CanESM5-1
  ensemble: r(1:25)i1p2f1
  grid: gn
  institute: CCCma
  version: v20190429
- dataset: CanESM5-1
  ensemble: r22i1p1f1
  grid: gn
  institute: CCCma
  version: v20190429
- dataset: CanESM5-1
  ensemble: r(24:39)i1p1f1
  grid: gn
  institute: CCCma
  version: v20190429
- dataset: CanESM5-1
  ensemble: r(41:50)i1p1f1
  grid: gn
  institute: CCCma
  version: v20190429
- dataset: CanESM5-CanOE
  ensemble: r(1:3)i1p2f1
  grid: gn
  institute: CCCma
  version: v20190429
- dataset: FGOALS-f3-L
  ensemble: r(1:3)i1p1f1
  grid: gn
  institute: CAS
  version: v20191007
- dataset: FGOALS-g3
  ensemble: r(1:5)i1p1f1
  grid: gn
  institute: CAS
  version: v20191012
- dataset: GISS-E2-1-G
  ensemble: r(1:6)i1p3f1
  grid: gn
  institute: NASA-GISS
  version: v20190702
- dataset: GISS-E2-1-G
  ensemble: r(8:10)i1p3f1
  grid: gn
  institute: NASA-GISS
  version: v20190702
- dataset: GISS-E2-1-G
  ensemble: r(101:102)i1p1f1
  grid: gn
  institute: NASA-GISS
  version: v20190815
- dataset: GISS-E2-1-G
  ensemble: r(1:5)i1p1f3
  grid: gn
  institute: NASA-GISS
  version: v20190903
- dataset: GISS-E2-1-G
  ensemble: r(1:11)i1p1f2
  grid: gn
  institute: NASA-GISS
  version: v20190903
- dataset: GISS-E2-1-G
  ensemble: r(1:4)i1p5f1
  grid: gn
  institute: NASA-GISS
  version: v20190905
- dataset: GISS-E2-1-G
  ensemble: r(6:10)i1p5f1
  grid: gn
  institute: NASA-GISS
  version: v20190905
- dataset: GISS-E2-1-G-CC
  ensemble: r1i1p1f1
  grid: gn
  institute: NASA-GISS
  version: v20190815
- dataset: GISS-E2-2-G
  ensemble: r(1:6)i1p1f1
  grid: gn
  institute: NASA-GISS
  version: v20191120
- dataset: GISS-E2-2-G
  ensemble: r(1:5)i1p3f1
  grid: gn
  institute: NASA-GISS
  version: v20211020
- dataset: ICON-ESM-LR
  ensemble: r(1:5)i1p1f1
  grid: gn
  institute: MPI-M
  version: v20210215
- dataset: INM-CM4-8
  ensemble: r1i1p1f1
  grid: gr1
  institute: INM
  version: v20190530
- dataset: INM-CM5-0
  ensemble: r1i1p1f1
  grid: gr1
  institute: INM
  version: v20190610
- dataset: INM-CM5-0
  ensemble: r3i1p1f1
  grid: gr1
  institute: INM
  version: v20190703
- dataset: INM-CM5-0
  ensemble: r2i1p1f1
  grid: gr1
  institute: INM
  version: v20190704
- dataset: INM-CM5-0
  ensemble: r4i1p1f1
  grid: gr1
  institute: INM
  version: v20190704
- dataset: INM-CM5-0
  ensemble: r5i1p1f1
  grid: gr1
  institute: INM
  version: v20190705
- dataset: INM-CM5-0
  ensemble: r(6:8)i1p1f1
  grid: gr1
  institute: INM
  version: v20190709
- dataset: INM-CM5-0
  ensemble: r9i1p1f1
  grid: gr1
  institute: INM
  version: v20190710
- dataset: INM-CM5-0
  ensemble: r10i1p1f1
  grid: gr1
  institute: INM
  version: v20190712
- dataset: MIROC-ES2L
  ensemble: r1i1000p1f2
  grid: gr
  institute: MIROC
  version: v20210317
- dataset: MIROC-ES2L
  ensemble: r(1:30)i1p1f2
  grid: gr
  institute: MIROC
  version: v20210317
- dataset: MIROC6
  ensemble: r(1:10)i1p1f1
  grid: gr
  institute: MIROC
  version: v20200421
- dataset: MPI-ESM-1-2-HAM
  ensemble: r(1:2)i1p1f1
  grid: gn
  institute: HAMMOZ-Consortium
  version: v20190627
- dataset: MPI-ESM-1-2-HAM
  ensemble: r3i1p1f1
  grid: gn
  institute: HAMMOZ-Consortium
  version: v20191218
- dataset: MPI-ESM1-2-HR
  ensemble: r(1:10)i1p1f1
  grid: gn
  institute: MPI-M
  version: v20190710
- dataset: MPI-ESM1-2-LR
  ensemble: r(1:10)i1p1f1
  grid: gn
  institute: MPI-M
  version: v20190710
- dataset: MPI-ESM1-2-LR
  ensemble: r(31:50)i1p1f1
  grid: gn
  institute: MPI-M
  version: v20190815
- dataset: MPI-ESM1-2-LR
  ensemble: r(11:30)i1p1f1
  grid: gn
  institute: MPI-M
  version: v20210901
- dataset: MPI-ESM1-2-LR
  ensemble: r1i2000p1f1
  grid: gn
  institute: MPI-M
  version: v20211412
- dataset: MRI-ESM2-0
  ensemble: r(1:5)i1p1f1
  grid: gr2z
  institute: MRI
  version: v20191210
- dataset: MRI-ESM2-0
  ensemble: r1i2p1f1
  grid: gr2z
  institute: MRI
  version: v20200303
- dataset: MRI-ESM2-0
  ensemble: r1i1000p1f1
  grid: gr2z
  institute: MRI
  version: v20201029
- dataset: MRI-ESM2-0
  ensemble: r(6:10)i1p1f1
  grid: gr2z
  institute: MRI
  version: v20210909
- dataset: NorESM2-LM
  ensemble: r1i1p1f1
  grid: grz
  institute: NCC
  version: v20190815
- dataset: NorESM2-LM
  ensemble: r(2:3)i1p1f1
  grid: grz
  institute: NCC
  version: v20190920
- dataset: NorESM2-LM
  ensemble: r1i1p4f1
  grid: grz
  institute: NCC
  version: v20230616
- dataset: NorESM2-MM
  ensemble: r1i1p1f1
  grid: grz
  institute: NCC
  version: v20191108
- dataset: NorESM2-MM
  ensemble: r2i1p1f1
  grid: grz
  institute: NCC
  version: v20200218
- dataset: NorESM2-MM
  ensemble: r3i1p1f1
  grid: grz
  institute: NCC
  version: v20200702
- dataset: SAM0-UNICON
  ensemble: r1i1p1f1
  grid: gn
  institute: SNU
  version: v20190323
