documentation:
  title: Get CMIP6 thetao-data for historical period.
  description: The recipe downloads climate data for LGM experiments, regrids the
    data to a 5x5 grid and provides the climatological average and standard deviations
    for the entire period and for each month.
  authors:
  - grusdt_britta
  maintainer:
  - grusdt_britta
preprocessors:
  general:
    regrid:
      target_grid: 5x5
      scheme: linear
    extract_levels:
      levels:
      - 0
      - 50
      - 200
      - 300
      scheme: linear_extrapolate
  climatological_mean:
    regrid:
      target_grid: 5x5
      scheme: linear
    extract_levels:
      levels:
      - 0
      - 50
      - 200
      - 300
      scheme: linear_extrapolate
    climate_statistics:
      operator: mean
      period: full
  climatological_monthly_mean:
    regrid:
      target_grid: 5x5
      scheme: linear
    extract_levels:
      levels:
      - 0
      - 50
      - 200
      - 300
      scheme: linear_extrapolate
    climate_statistics:
      operator: mean
      period: monthly
  standard_dev:
    regrid:
      target_grid: 5x5
      scheme: linear
    extract_levels:
      levels:
      - 0
      - 50
      - 200
      - 300
      scheme: linear_extrapolate
    climate_statistics:
      operator: std_dev
      period: full
  standard_dev_monthly:
    regrid:
      target_grid: 5x5
      scheme: linear
    extract_levels:
      levels:
      - 0
      - 50
      - 200
      - 300
      scheme: linear_extrapolate
    climate_statistics:
      operator: std_dev
      period: monthly
  default: {}
diagnostics:
  lgm:
    variables:
      thetao_CLIM:
        short_name: thetao
        preprocessor: climatological_mean
        variable_long_name: sea_water_potential_temperature
        mip: Omon
        mip_era: CMIP6
        exp: lgm
        activity: PMIP
        grid: gn
        project: CMIP6
      thetao_CLIM-mon:
        short_name: thetao
        preprocessor: climatological_monthly_mean
        variable_long_name: sea_water_potential_temperature
        mip: Omon
        mip_era: CMIP6
        exp: lgm
        activity: PMIP
        grid: gn
        project: CMIP6
      thetao_STD:
        short_name: thetao
        preprocessor: standard_dev
        variable_long_name: sea_water_potential_temperature
        mip: Omon
        mip_era: CMIP6
        exp: lgm
        activity: PMIP
        grid: gn
        project: CMIP6
      thetao_STD-mon:
        short_name: thetao
        preprocessor: standard_dev_monthly
        variable_long_name: sea_water_potential_temperature
        mip: Omon
        mip_era: CMIP6
        exp: lgm
        activity: PMIP
        grid: gn
        project: CMIP6
    scripts: null
datasets:
- dataset: CESM2-FV2
  ensemble: r1i2p2f1
  institute: NCAR
  version: v20220915
- dataset: CESM2-WACCM-FV2
  ensemble: r1i2p2f1
  institute: NCAR
  version: v20220915
- dataset: MPI-ESM1-2-LR
  ensemble: r1i1p1f1
  institute: MPI-M
  version: v20190710
