documentation:
  title: Get CMIP5 tas-data for historical period.
  description: The recipe downloads climate data for LGM experiments, regrids the
    data to a 5x5 grid and provides the climatological average and standard deviations
    for the entire period and for each month.
  authors:
  - grusdt_britta
  maintainer:
  - grusdt_britta
preprocessors:
  general:
    regrid:
      target_grid: 5x5
      scheme: linear
  climatological_mean:
    regrid:
      target_grid: 5x5
      scheme: linear
    climate_statistics:
      operator: mean
      period: full
  climatological_monthly_mean:
    regrid:
      target_grid: 5x5
      scheme: linear
    climate_statistics:
      operator: mean
      period: monthly
  standard_dev:
    regrid:
      target_grid: 5x5
      scheme: linear
    climate_statistics:
      operator: std_dev
      period: full
  standard_dev_monthly:
    regrid:
      target_grid: 5x5
      scheme: linear
    climate_statistics:
      operator: std_dev
      period: monthly
  default: {}
diagnostics:
  lgm:
    variables:
      tas_CLIM:
        short_name: tas
        preprocessor: climatological_mean
        variable_long_name: Near-Surface Air Temperature
        mip: Amon
        mip_era: CMIP5
        exp: lgm
        project: CMIP5
      tas_CLIM-mon:
        short_name: tas
        preprocessor: climatological_monthly_mean
        variable_long_name: Near-Surface Air Temperature
        mip: Amon
        mip_era: CMIP5
        exp: lgm
        project: CMIP5
      tas_STD:
        short_name: tas
        preprocessor: standard_dev
        variable_long_name: Near-Surface Air Temperature
        mip: Amon
        mip_era: CMIP5
        exp: lgm
        project: CMIP5
      tas_STD-mon:
        short_name: tas
        preprocessor: standard_dev_monthly
        variable_long_name: Near-Surface Air Temperature
        mip: Amon
        mip_era: CMIP5
        exp: lgm
        project: CMIP5
    scripts: null
datasets:
- dataset: CCSM4
  ensemble: r1i1p1
  institute: NCAR
  version: v20120203
- dataset: CCSM4
  ensemble: r2i1p1
  institute: NCAR
  version: v20120604
- dataset: CNRM-CM5
  ensemble: r1i1p1
  institute: CNRM-CERFACS
  version: v20120530
- dataset: FGOALS-g2
  ensemble: r1i1p1
  institute: LASG-CESS
  version: v1
- dataset: GISS-E2-R
  ensemble: r1i1p(150:151)
  institute: NASA-GISS
  version: v20160510
- dataset: IPSL-CM5A-LR
  ensemble: r1i1p1
  institute: IPSL
  version: v20120114
- dataset: MIROC-ESM
  ensemble: r1i1p1
  institute: MIROC
  version: v20120710
- dataset: MPI-ESM-P
  ensemble: r1i1p1
  institute: MPI-M
  version: v20120602
- dataset: MPI-ESM-P
  ensemble: r1i1p2
  institute: MPI-M
  version: v20120713
- dataset: MRI-CGCM3
  ensemble: r1i1p1
  institute: MRI
  version: v20120701
