base_path: /albedo/work/projects/p_forclima/preproc_data_esmvaltool/climwip/climwip-simplified_20240926_140539
target_dir: /albedo/work/projects/p_forclima/britta/similarityweights-output/climwip-simplified

models_project_name: CMIP5

# SETTINGS FOR PLOTS BASED ON COMPUTED WEIGHTS
diagnostics:
  - ANOM # precomputed anomalies wrt some reference period
variables: 
  - tas
name_full_period: period_1960_2100 # the name of the entire time period considered for our data recipes
