base_path: /albedo/work/projects/p_forclima/preproc_data_esmvaltool/climwip/climwip-simplified_20240930_055424
target_dir: /albedo/work/projects/p_forclima/britta/similarityweights-output/climwip-simplified

diagnostics:
  - CLIM

variables: 
  - tas


models_project_name: CMIP5
obs_data_name: ERA5


# SETTINGS FOR PLOTS BASED ON COMPUTED WEIGHTS
diagnostics:
  - CLIM 
variables: 
  - tas
name_full_period: period_2081_2100_temp_map # the name of the entire time period considered for our data recipes
name_ref_period: period_1995_2014_temp_map
