path_to_recipes: /albedo/work/projects/p_forclima/preproc_data_esmvaltool/historical
prefix_recipes: recipe_historical
target_dir: /albedo/home/brgrus001/SimilarityWeights/output

models_project_name: CMIP6
obs_data_name: ERA5

diagnostics:
  - CLIM

variables: 
  - tas
  - pr
  - tos

name_ref_period: historical1
name_obs_period: historical1

weight_contributions:
  performance: 0.5
  independence: 0.5

weights_variables:
  performance:
    tas: 1
    tos: 1
    pr: 1

  independence:
    tas: 0.5
    tos: 0.125
    pr: 0.25