base_path: /Users/brgrus001/output-from-albedo/historical/recipe_historical_pr
target_dir: /Users/brgrus001/SimilarityWeights/output

diagnostics:
  - CLIM

variables: 
  - pr

name_ref_period: historical1
experiment: historical #name_full_period: full

models_project_name: CMIP6
obs_data_name: ERA5

weight_contributions:
  performance: 0.5
  independence: 0.5

weights_variables:
  performance:
    pr: 1

  independence:
    pr: 1